sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
addons:
  code_climate:
    repo_token: dff6f0cc0775e0f814f7880fa263bb7d44ebf97855e560093132dde347a3bb46
after_script:
  - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
